# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0erecommendation\"u\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\x12\x10\n\x08movie_id\x18\x03 \x01(\t\x12\r\n\x05\x61lpha\x18\x04 \x01(\x01\x12\x15\n\rtotal_watched\x18\x05 \x01(\x05\"E\n\x13MovieRecommendation\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\"V\n\x16RecommendationResponse\x12<\n\x0frecommendations\x18\x01 \x03(\x0b\x32#.recommendation.MovieRecommendation\"7\n\x0eSimilarRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"O\n\x0fSimilarResponse\x12<\n\x0frecommendations\x18\x01 \x03(\x0b\x32#.recommendation.MovieRecommendation\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8e\x02\n\x15RecommendationService\x12Z\n\tRecommend\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\x12P\n\rSimilarMovies\x12\x1e.recommendation.SimilarRequest\x1a\x1f.recommendation.SimilarResponse\x12G\n\x06Health\x12\x1d.recommendation.HealthRequest\x1a\x1e.recommendation.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=33
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=150
  _globals['_MOVIERECOMMENDATION']._serialized_start=152
  _globals['_MOVIERECOMMENDATION']._serialized_end=221
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=223
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=309
  _globals['_SIMILARREQUEST']._serialized_start=311
  _globals['_SIMILARREQUEST']._serialized_end=366
  _globals['_SIMILARRESPONSE']._serialized_start=368
  _globals['_SIMILARRESPONSE']._serialized_end=447
  _globals['_HEALTHREQUEST']._serialized_start=449
  _globals['_HEALTHREQUEST']._serialized_end=464
  _globals['_HEALTHRESPONSE']._serialized_start=466
  _globals['_HEALTHRESPONSE']._serialized_end=498
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=501
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
