# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub(object):
    """Service boundary between backend-node and the Python recommendation engine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommend = channel.unary_unary(
                '/recommendation.RecommendationService/Recommend',
                request_serializer=service__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=service__pb2.RecommendationResponse.FromString,
                _registered_method=True)
        self.SimilarMovies = channel.unary_unary(
                '/recommendation.RecommendationService/SimilarMovies',
                request_serializer=service__pb2.SimilarRequest.SerializeToString,
                response_deserializer=service__pb2.SimilarResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/recommendation.RecommendationService/Health',
                request_serializer=service__pb2.HealthRequest.SerializeToString,
                response_deserializer=service__pb2.HealthResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """Service boundary between backend-node and the Python recommendation engine.
    """

    def Recommend(self, request, context):
        """Returns recommendations for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimilarMovies(self, request, context):
        """Returns movies similar to the provided movie id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Simple health check for the engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=service__pb2.RecommendationRequest.FromString,
                    response_serializer=service__pb2.RecommendationResponse.SerializeToString,
            ),
            'SimilarMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.SimilarMovies,
                    request_deserializer=service__pb2.SimilarRequest.FromString,
                    response_serializer=service__pb2.SimilarResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=service__pb2.HealthRequest.FromString,
                    response_serializer=service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """Service boundary between backend-node and the Python recommendation engine.
    """

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/Recommend',
            service__pb2.RecommendationRequest.SerializeToString,
            service__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimilarMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/SimilarMovies',
            service__pb2.SimilarRequest.SerializeToString,
            service__pb2.SimilarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/Health',
            service__pb2.HealthRequest.SerializeToString,
            service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
